### ISSUE TITLE
No channels and recordings

### ISSUE THREAD

**Issue by Skywalker3008** [knackebrot/jellyfin-plugin-enigma2#11]
Have the plugin installed on a Windows PC and a Mac, each with your plugin. If I now enter my data from the VU+, it will not find any channels or recordings. Am I doing anything wrong?

Log:
[2022-07-13 09:44:23.166 +02:00] [INF] [16] Jellyfin.Plugin.Enigma2.LiveTvService: [Enigma2] Start GetTimerAsync, retrieve the 'Pending' recordings
[2022-07-13 09:44:23.174 +02:00] [INF] [16] Jellyfin.Plugin.Enigma2.LiveTvService: [Enigma2] Start EnsureConnectionAsync
[2022-07-13 09:44:23.174 +02:00] [INF] [16] Jellyfin.Plugin.Enigma2.LiveTvService: [Enigma2] EnsureConnectionAsync HostName: 192.168.1.60
[2022-07-13 09:44:23.175 +02:00] [INF] [16] Jellyfin.Plugin.Enigma2.LiveTvService: [Enigma2] EnsureConnectionAsync StreamingPort: 8001
[2022-07-13 09:44:23.176 +02:00] [INF] [16] Jellyfin.Plugin.Enigma2.LiveTvService: [Enigma2] EnsureConnectionAsync WebInterfacePort: 2100
[2022-07-13 09:44:23.176 +02:00] [INF] [16] Jellyfin.Plugin.Enigma2.LiveTvService: [Enigma2] EnsureConnectionAsync WebInterfaceUsername: ********
[2022-07-13 09:44:23.177 +02:00] [INF] [16] Jellyfin.Plugin.Enigma2.LiveTvService: [Enigma2] EnsureConnectionAsync WebInterfaceUsername: ********
[2022-07-13 09:44:23.177 +02:00] [INF] [16] Jellyfin.Plugin.Enigma2.LiveTvService: [Enigma2] EnsureConnectionAsync UseLoginForStreams: False
[2022-07-13 09:44:23.178 +02:00] [INF] [16] Jellyfin.Plugin.Enigma2.LiveTvService: [Enigma2] EnsureConnectionAsync UseSecureHTTPS: False
[2022-07-13 09:44:23.179 +02:00] [INF] [16] Jellyfin.Plugin.Enigma2.LiveTvService: [Enigma2] EnsureConnectionAsync UseSecureHTTPSForStreams: False
[2022-07-13 09:44:23.179 +02:00] [INF] [16] Jellyfin.Plugin.Enigma2.LiveTvService: [Enigma2] EnsureConnectionAsync OnlyOneBouquet: True
[2022-07-13 09:44:23.180 +02:00] [INF] [16] Jellyfin.Plugin.Enigma2.LiveTvService: [Enigma2] EnsureConnectionAsync TVBouquet: NEU
[2022-07-13 09:44:23.180 +02:00] [INF] [16] Jellyfin.Plugin.Enigma2.LiveTvService: [Enigma2] EnsureConnectionAsync ZapToChannel: False
[2022-07-13 09:44:23.181 +02:00] [INF] [16] Jellyfin.Plugin.Enigma2.LiveTvService: [Enigma2] EnsureConnectionAsync FetchPiconsFromWebInterface: False
[2022-07-13 09:44:23.182 +02:00] [INF] [16] Jellyfin.Plugin.Enigma2.LiveTvService: [Enigma2] EnsureConnectionAsync PiconsPath: 
[2022-07-13 09:44:23.182 +02:00] [INF] [16] Jellyfin.Plugin.Enigma2.LiveTvService: [Enigma2] EnsureConnectionAsync RecordingPath: 
[2022-07-13 09:44:23.183 +02:00] [INF] [16] Jellyfin.Plugin.Enigma2.LiveTvService: [Enigma2] EnsureConnectionAsync EnableDebugLogging: True
[2022-07-13 09:44:23.183 +02:00] [ERR] [16] Jellyfin.Plugin.Enigma2.LiveTvService: [Enigma2] Picons location must be configured if Fetch Picons from Web Service is disabled.
[2022-07-13 09:44:23.184 +02:00] [ERR] [16] Emby.Server.Implementations.LiveTv.LiveTvManager: Error getting recordings
System.InvalidOperationException: Enigma2 Picons location must be configured if Fetch Picons from Web Service is disabled.
   at Jellyfin.Plugin.Enigma2.LiveTvService.EnsureConnectionAsync(CancellationToken cancellationToken)
   at Jellyfin.Plugin.Enigma2.LiveTvService.GetTimersAsync(CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.LiveTvManager.<>c__DisplayClass70_0.<<GetTimers>b__0>d.MoveNext()
[2022-07-13 09:44:23.757 +02:00] [INF] [25] Jellyfin.Plugin.Enigma2.LiveTvService: [Enigma2] Start GetSeriesTimersAsync

**Comment by det-peralta** [comment]
Did you find a solution? I have the same problem.

**Comment by knackebrot** [comment]
```
Error getting recordings
System.InvalidOperationException: Enigma2 Picons location must be configured if Fetch Picons from Web Service is disabled.
```
