### ISSUE TITLE
plugin not working

### ISSUE THREAD

**Issue by fabfive23** [knackebrot/jellyfin-plugin-enigma2#3]
Hi 

i am running jellyfin Version: 10.7.6 on a ubuntu 18.04

I can install the plugin without a problem. 
configuring it is possible as well

but when i select it in the menu i get the following in the logs:

[2021-06-29 22:46:48.163 +02:00] [INF] [VuPlus] Start GetRecordingsAsync, retrieve all 'Inprogress' and 'Completed' recordings 
[2021-06-29 22:46:48.164 +02:00] [INF] [VuPlus] Start EnsureConnectionAsync
[2021-06-29 22:46:48.164 +02:00] [INF] [VuPlus] EnsureConnectionAsync HostName: http://192.168.23.3
[2021-06-29 22:46:48.165 +02:00] [INF] [VuPlus] EnsureConnectionAsync StreamingPort: 8001
[2021-06-29 22:46:48.165 +02:00] [INF] [VuPlus] EnsureConnectionAsync WebInterfacePort: 80
[2021-06-29 22:46:48.165 +02:00] [INF] [VuPlus] EnsureConnectionAsync WebInterfaceUsername: 
[2021-06-29 22:46:48.166 +02:00] [INF] [VuPlus] EnsureConnectionAsync WebInterfacePassword: 
[2021-06-29 22:46:48.166 +02:00] [INF] [VuPlus] EnsureConnectionAsync UseSecureHTTPS: False
[2021-06-29 22:46:48.167 +02:00] [INF] [VuPlus] EnsureConnectionAsync OnlyOneBouquet: True
[2021-06-29 22:46:48.167 +02:00] [INF] [VuPlus] EnsureConnectionAsync TVBouquet: Favourites
[2021-06-29 22:46:48.167 +02:00] [INF] [VuPlus] EnsureConnectionAsync ZapToChannel: False
[2021-06-29 22:46:48.167 +02:00] [INF] [VuPlus] EnsureConnectionAsync FetchPiconsFromWebInterface: True
[2021-06-29 22:46:48.168 +02:00] [INF] [VuPlus] EnsureConnectionAsync PiconsPath: /tmp/
[2021-06-29 22:46:48.168 +02:00] [INF] [VuPlus] EnsureConnectionAsync RecordingPath: /hdd/movie/
[2021-06-29 22:46:48.168 +02:00] [INF] [VuPlus] EnsureConnectionAsync EnableDebugLogging: True
[2021-06-29 22:46:48.173 +02:00] [INF] [VuPlus] EnsureConnectionAsync Validation of config parameters completed
[2021-06-29 22:46:48.173 +02:00] [INF] [VuPlus] Start InitiateSession, validates connection and returns Bouquet reference if required
[2021-06-29 22:46:48.183 +02:00] [ERR] Error processing request. URL "GET" "/LiveTv/Recordings".
System.Net.Http.HttpRequestException: Name or service not known (http:80)
 ---> System.Net.Sockets.SocketException (0xFFFDFFFF): Name or service not known
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetStreamAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at MediaBrowser.Plugins.VuPlus.LiveTvService.InitiateSession(CancellationToken cancellationToken, String tvBouquet)
   at MediaBrowser.Plugins.VuPlus.LiveTvService.EnsureConnectionAsync(CancellationToken cancellationToken)
   at MediaBrowser.Plugins.VuPlus.LiveTvService.GetAllRecordingsAsync(CancellationToken cancellationToken)
   at MediaBrowser.Plugins.VuPlus.RecordingsChannel.GetRecordingGroups(InternalChannelItemQuery query, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Channels.ChannelManager.GetChannelItems(IChannel channel, User user, String externalFolderId, Nullable`1 sortField, Boolean sortDescending, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Channels.ChannelManager.GetChannelItemsInternal(InternalItemsQuery query, IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Channels.ChannelManager.RefreshLatestChannelItems(IChannel channel, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Channels.ChannelManager.GetChannelsInternal(ChannelQuery query)
   at Emby.Server.Implementations.LiveTv.LiveTvManager.GetRecordingFolders(User user, Boolean refreshChannels)
   at Emby.Server.Implementations.LiveTv.LiveTvManager.GetEmbyRecordings(RecordingQuery query, DtoOptions dtoOptions, User user)
   at Emby.Server.Implementations.LiveTv.LiveTvManager.GetRecordings(RecordingQuery query, DtoOptions options)
   at Jellyfin.Api.Controllers.LiveTvController.GetRecordings(String channelId, Nullable`1 userId, Nullable`1 startIndex, Nullable`1 limit, Nullable`1 status, Nullable`1 isInProgress, String seriesTimerId, Nullable`1 enableImages, Nullable`1 imageTypeLimit, ImageType[] enableImageTypes, ItemFields[] fields, Nullable`1 enableUserData, Nullable`1 isMovie, Nullable`1 isSeries, Nullable`1 isKids, Nullable`1 isSports, Nullable`1 isNews, Nullable`1 isLibraryItem, Boolean enableTotalRecordCount)

 a tcpdump shows, no connection is even made.
my guess is something is missing cause it tries to make the connection to: (http:80)

thx for any hints.

Fab

**Comment by knackebrot** [comment]
Try removing http:// from hostname.

**Comment by fabfive23** [comment]
thx, i'm one step futher , thought  i tried that in the past.

in a tcpdump i see request like: 

http://192.168.23.3/web/getservices
http://192.168.23.3/web/movielist

but nothing is showing up.

when doing http://192.168.23.3/web/movielist?dirname=/media/hdd/movies/  with curl i get all the recordings 
but i do not see such requests by jellyfin with RecordingPath set correctly

**Comment by fabfive23** [comment]
I did some more tests.
LiveTV is working now, after i updated openwebif to the latest version.

but still now recordings.

**Comment by triclonedave** [comment]
Jellyfin 10.10.6 and OpenViX 6.7.005 (2025-03-03-Release) Recorded programs are accessible, but Live and EPG don't function, anyone else experiencing this - new setup
